const logger = require('../utils/logger');
const hardcodedApps = require('./hardcodedApps');
const fetch = require('node-fetch');

class GroqService {
  async generateAppCode(prompt, framework = 'react') {
    const normalizedPrompt = prompt.toLowerCase();
    const quickKey = Object.keys(hardcodedApps).find(
      key => normalizedPrompt.includes(key.toLowerCase())
    );
    if (quickKey && hardcodedApps[quickKey]) {
      // Return hardcoded app instead of calling Groq
      return {
        files: hardcodedApps[quickKey].files,
        summary: hardcodedApps[quickKey].summary,
        features: [],
        dependencies: []
      };
    }
    // Otherwise, call Groq API
    try {
      const groqApiKey = process.env.GROQ_API_KEY;
      if (!groqApiKey) throw new Error('GROQ_API_KEY not set in environment');
      const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${groqApiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama3-70b-8192',
          messages: [
            { role: 'system', content: this.getSystemPrompt(framework) },
            { role: 'user', content: `Generate a high-quality, runnable ${framework} app. ${prompt}\nReturn only the main App component code as /App.js, and a runnable HTML preview as /index.html. Also provide a summary of the app.` }
          ],
          max_tokens: 4096
        })
      });
      const data = await groqRes.json();
      if (!data.choices || !data.choices[0] || !data.choices[0].message || !data.choices[0].message.content) {
        throw new Error('Groq API did not return valid content');
      }
      // Parse the response (expecting code blocks for /App.js and /index.html, and a summary)
      const content = data.choices[0].message.content;
      // Simple parsing: look for code blocks and summary
      const appJsMatch = content.match(/\/App\.js[\s\S]*?```[a-z]*([\s\S]*?)```/i) || content.match(/```[a-z]*([\s\S]*?)```/i);
      const indexHtmlMatch = content.match(/\/index\.html[\s\S]*?```[a-z]*([\s\S]*?)```/i);
      const summaryMatch = content.match(/summary[:\-\s]*([\s\S]*?)(?:```|$)/i);
      const appJs = appJsMatch ? appJsMatch[1].trim() : '';
      const indexHtml = indexHtmlMatch ? indexHtmlMatch[1].trim() : '';
      const summary = summaryMatch ? summaryMatch[1].trim() : 'App generated by Groq.';
      if (!appJs) throw new Error('Groq did not return /App.js code');
      return {
        files: {
          '/App.js': appJs,
          '/index.html': indexHtml || ''
        },
        summary,
        features: this.extractFeatures(appJs),
        dependencies: this.extractDependencies(appJs, framework)
      };
    } catch (error) {
      logger.error('Groq API error:', error);
      throw new Error(`Code generation failed: ${error.message}`);
    }
  }

  getSystemPrompt(framework) {
    const prompts = {
      react: `You are an expert React developer. Generate complete, functional React applications with the following requirements:
- Use modern React with hooks
- Include proper error handling
- Add responsive design with Tailwind CSS
- Include interactive features
- Use semantic HTML
- Add smooth animations and transitions
- Ensure accessibility standards
- Include loading states
- Add proper TypeScript types if needed
- Make it production-ready with best practices

Return only the React component code as a function component named "App", without explanations.`
    };
    return prompts[framework] || prompts.react;
  }

  extractFeatures(code) {
    const features = [];
    if (code.includes('dark') || code.includes('theme')) features.push('dark-mode');
    if (code.includes('@media') || code.includes('responsive')) features.push('responsive');
    if (code.includes('animation') || code.includes('transition')) features.push('animations');
    if (code.includes('serviceWorker') || code.includes('manifest')) features.push('pwa');
    if (code.includes('interface') || code.includes('type:')) features.push('typescript');
    if (code.includes('className=') || code.includes('tailwind')) features.push('tailwind');
    return features;
  }

  extractDependencies(code, framework) {
    const baseDeps = {
      react: [
        { name: 'react', version: '^18.2.0' },
        { name: 'react-dom', version: '^18.2.0' }
      ]
    };
    const deps = baseDeps[framework] || baseDeps.react;
    if (code.includes('tailwind') || code.includes('className=')) {
      deps.push({ name: 'tailwindcss', version: '^3.3.0' });
    }
    return deps;
  }
}

module.exports = new GroqService();